In [ ]:
import pandas as pd
df=pd.read_csv("car data.csv")
df.isna().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [ ]:
df=df.drop("Car_Name", axis=1)
df

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0    2014           3.35           5.59       27000    Petrol      Dealer   
1    2013           4.75           9.54       43000    Diesel      Dealer   
2    2017           7.25           9.85        6900    Petrol      Dealer   
3    2011           2.85           4.15        5200    Petrol      Dealer   
4    2014           4.60           6.87       42450    Diesel      Dealer   
..    ...            ...            ...         ...       ...         ...   
296  2016           9.50          11.60       33988    Diesel      Dealer   
297  2015           4.00           5.90       60000    Petrol      Dealer   
298  2009           3.35          11.00       87934    Petrol      Dealer   
299  2017          11.50          12.50        9000    Diesel      Dealer   
300  2016           5.30           5.90        5464    Petrol      Dealer   

    Transmission  Owner  
0         Manual      0  
1         Manual      0  
2         Manual      0  
3         Manual      0  
4         Manual      0  
..           ...    ...  
296       Manual      0  
297       Manual      0  
298       Manual      0  
299       Manual      0  
300       Manual      0  

[301 rows x 8 columns]

In [ ]:
df["Age"]=2025-df['Year']
df

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0    2014           3.35           5.59       27000    Petrol      Dealer   
1    2013           4.75           9.54       43000    Diesel      Dealer   
2    2017           7.25           9.85        6900    Petrol      Dealer   
3    2011           2.85           4.15        5200    Petrol      Dealer   
4    2014           4.60           6.87       42450    Diesel      Dealer   
..    ...            ...            ...         ...       ...         ...   
296  2016           9.50          11.60       33988    Diesel      Dealer   
297  2015           4.00           5.90       60000    Petrol      Dealer   
298  2009           3.35          11.00       87934    Petrol      Dealer   
299  2017          11.50          12.50        9000    Diesel      Dealer   
300  2016           5.30           5.90        5464    Petrol      Dealer   

    Transmission  Owner  Age  
0         Manual      0   11  
1         Manual      0   12  
2         Manual      0    8  
3         Manual      0   14  
4         Manual      0   11  
..           ...    ...  ...  
296       Manual      0    9  
297       Manual      0   10  
298       Manual      0   16  
299       Manual      0    8  
300       Manual      0    9  

[301 rows x 9 columns]

In [ ]:
df=df.drop("Year", axis=1)
df

Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0             3.35           5.59       27000    Petrol      Dealer   
1             4.75           9.54       43000    Diesel      Dealer   
2             7.25           9.85        6900    Petrol      Dealer   
3             2.85           4.15        5200    Petrol      Dealer   
4             4.60           6.87       42450    Diesel      Dealer   
..             ...            ...         ...       ...         ...   
296           9.50          11.60       33988    Diesel      Dealer   
297           4.00           5.90       60000    Petrol      Dealer   
298           3.35          11.00       87934    Petrol      Dealer   
299          11.50          12.50        9000    Diesel      Dealer   
300           5.30           5.90        5464    Petrol      Dealer   

    Transmission  Owner  Age  
0         Manual      0   11  
1         Manual      0   12  
2         Manual      0    8  
3         Manual      0   14  
4         Manual      0   11  
..           ...    ...  ...  
296       Manual      0    9  
297       Manual      0   10  
298       Manual      0   16  
299       Manual      0    8  
300       Manual      0    9  

[301 rows x 8 columns]

In [ ]:
pd.get_dummies(df)

Selling_Price  Present_Price  Kms_Driven  Owner  Age  Fuel_Type_CNG  \
0             3.35           5.59       27000      0   11          False   
1             4.75           9.54       43000      0   12          False   
2             7.25           9.85        6900      0    8          False   
3             2.85           4.15        5200      0   14          False   
4             4.60           6.87       42450      0   11          False   
..             ...            ...         ...    ...  ...            ...   
296           9.50          11.60       33988      0    9          False   
297           4.00           5.90       60000      0   10          False   
298           3.35          11.00       87934      0   16          False   
299          11.50          12.50        9000      0    8          False   
300           5.30           5.90        5464      0    9          False   

     Fuel_Type_Diesel  Fuel_Type_Petrol  Seller_Type_Dealer  \
0               False              True                True   
1                True             False                True   
2               False              True                True   
3               False              True                True   
4                True             False                True   
..                ...               ...                 ...   
296              True             False                True   
297             False              True                True   
298             False              True                True   
299              True             False                True   
300             False              True                True   

     Seller_Type_Individual  Transmission_Automatic  Transmission_Manual  
0                     False                   False                 True  
1                     False                   False                 True  
2                     False                   False                 True  
3                     False                   False                 True  
4                     False                   False                 True  
..                      ...                     ...                  ...  
296                   False                   False                 True  
297                   False                   False                 True  
298                   False                   False                 True  
299                   False                   False                 True  
300                   False                   False                 True  

[301 rows x 12 columns]

In [ ]:
df=pd.get_dummies(df, drop_first=True)
df

Selling_Price  Present_Price  Kms_Driven  Owner  Age  Fuel_Type_Diesel  \
0             3.35           5.59       27000      0   11             False   
1             4.75           9.54       43000      0   12              True   
2             7.25           9.85        6900      0    8             False   
3             2.85           4.15        5200      0   14             False   
4             4.60           6.87       42450      0   11              True   
..             ...            ...         ...    ...  ...               ...   
296           9.50          11.60       33988      0    9              True   
297           4.00           5.90       60000      0   10             False   
298           3.35          11.00       87934      0   16             False   
299          11.50          12.50        9000      0    8              True   
300           5.30           5.90        5464      0    9             False   

     Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual  
0                True                   False                 True  
1               False                   False                 True  
2                True                   False                 True  
3                True                   False                 True  
4               False                   False                 True  
..                ...                     ...                  ...  
296             False                   False                 True  
297              True                   False                 True  
298              True                   False                 True  
299             False                   False                 True  
300              True                   False                 True  

[301 rows x 9 columns]

In [ ]:
# Target is "selling price"
y=df["Selling_Price"]
x=df.drop("Selling_Price", axis=1)
print(x.shape, y.shape)

(301, 8) (301,)


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=2)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(240, 8) (61, 8)
(240,) (61,)


In [ ]:
240+61

301

In [ ]:
301*0.2

60.2

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_train, y_train)

In [ ]:
lr.coef_
# y=a+bx1+cx2+dX3+...+iX8
# b to i

array([ 4.28802981e-01, -5.92316903e-06, -8.49009727e-01, -4.06411225e-01,
        2.86056285e+00,  7.03103550e-01, -1.07477347e+00, -1.50897975e+00])

In [ ]:
print(x.columns)
print(y)

Index(['Present_Price', 'Kms_Driven', 'Owner', 'Age', 'Fuel_Type_Diesel',
       'Fuel_Type_Petrol', 'Seller_Type_Individual', 'Transmission_Manual'],
      dtype='object')
0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...  
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64


In [ ]:
lr.intercept_
# a

np.float64(6.850757321843108)

In [ ]:
y_pred=lr.predict(x_test)
y_pred

array([10.57889241,  0.71754255,  4.23613904,  5.17855444,  9.75533583,
        4.20615652,  2.6748089 ,  7.63221623,  0.17032381,  5.13283747,
        6.15727726,  6.44545506,  2.11900126,  7.6644102 ,  1.91710055,
        1.71680788,  2.02672159,  1.85294787,  9.56717323,  4.23076317,
        1.48724915,  9.36189904,  1.46103587,  9.54572517,  0.82954545,
        8.32266051,  1.53698563, -3.16293717,  4.2127377 ,  2.10385587,
        3.42279444,  3.71284702,  5.54538889,  7.6834828 , -1.89757368,
        7.06591847,  8.46027656,  5.77704136,  6.10531922,  6.52919752,
       16.08564344,  2.07410694,  1.05462465, -0.44710144,  7.06940454,
        6.73548589,  0.98609923,  7.08961114, 14.16420523,  3.00434598,
        8.2871215 , -0.87862345,  8.8814273 ,  1.15099681,  2.11848057,
       -0.82641923,  0.69287067,  9.88583992, -0.45444272, -2.41051663,
       10.28627971])

In [ ]:
from sklearn import metrics
print("MSE:", metrics.mean_squared_error(y_test, y_pred))

MSE: 2.750689262139754


In [ ]:
import numpy as np

In [ ]:
test_data=np.array([6.7, 10000, 0, 7, 1, 0,0,1])
test_data=test_data.reshape(1,8)

In [ ]:
lr.predict(test_data)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8.17121013])

In [ ]:
df1=pd.read_csv("advertising.csv")
df1.isna().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [ ]:
y1=df1["Sales"]
x1=df1.drop("Sales", axis=1)
print(x1.shape, y1.shape)

(200, 3) (200,)


In [ ]:
x_train, x_test, y_train, y_test=train_test_split(x1, y1, test_size=0.2, random_state=2)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(160, 3) (40, 3)
(160,) (40,)


In [ ]:
model=lr.fit(x_train, y_train)

In [ ]:
lr.coef_

array([0.05536768, 0.102883  , 0.00233839])

In [ ]:
print(x1.columns)
print(y1)

Index(['TV', 'Radio', 'Newspaper'], dtype='object')
0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64


In [ ]:
lr.intercept_

np.float64(4.499831369256482)

In [ ]:
y_pred=lr.predict(x_test)
y_pred

array([15.81794247, 10.15032354,  8.26737799, 18.25580684, 18.06466407,
       17.24354571,  8.81294515, 22.04513076, 12.38208193, 21.03691149,
        9.58287515, 20.13791992, 10.69692702,  9.05217041, 17.19403767,
       10.33653542,  8.63490536, 17.27389797, 18.24930692, 19.29279069,
       18.94026036, 19.46168254, 11.11298733, 10.6675807 , 18.0316489 ,
       14.58414874, 16.58323824,  9.27911751, 18.82160438, 17.18558892,
       20.11211809, 16.22950562, 15.87936272, 14.05507975,  7.89699942,
       12.12455603, 21.74608041, 21.4076981 , 19.58225049, 19.50042709])

In [ ]:
print("MSE:", metrics.mean_squared_error(y_test, y_pred))

MSE: 3.091721330322738


# **Simple Polynomial Regression**

In [ ]:
df=pd.read_csv("temp.csv")
df

sno  Temperature  Pressure
0    1            0    0.0002
1    2           20    0.0012
2    3           40    0.0060
3    4           60    0.0300
4    5           80    0.0900
5    6          100    0.2700

In [ ]:
df=df.drop("sno", axis=1)
df

Temperature  Pressure
0            0    0.0002
1           20    0.0012
2           40    0.0060
3           60    0.0300
4           80    0.0900
5          100    0.2700

In [ ]:
y=df["Pressure"]
x=df.drop("Pressure", axis=1)
print(x.shape, y.shape)

(6, 1) (6,)


In [210]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x)
x_poly

array([[1.0e+00, 0.0e+00, 0.0e+00],
       [1.0e+00, 2.0e+01, 4.0e+02],
       [1.0e+00, 4.0e+01, 1.6e+03],
       [1.0e+00, 6.0e+01, 3.6e+03],
       [1.0e+00, 8.0e+01, 6.4e+03],
       [1.0e+00, 1.0e+02, 1.0e+04]])

In [211]:
print(x_poly.shape)

(6, 3)


In [ ]:
x_train, x_test, y_train, y_test=train_test_split(x_poly, y, test_size=0.2)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(4, 3) (2, 3)
(4,) (2,)


In [ ]:
lr=LinearRegression()
model=lr.fit(x_train, y_train)

In [ ]:
lr.coef_

array([ 0.00000000e+00, -2.23878205e-03,  4.87916667e-05])

In [ ]:
lr.intercept_

np.float64(0.003080769230769914)