In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("ljtemp.csv")
df=df.drop("Point", axis=1)
df

x1  x2  class
0   1   2      0
1   2   3      0
2   3   1      1
3   6   5      1

In [3]:
y=df["class"]
x=df.drop("class", axis=1)
print(x.shape, y.shape)

(4, 2) (4,)


In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=2)

In [6]:
x_train

x1  x2
3   6   5
1   2   3
0   1   2

In [7]:
x_test

x1  x2
2   3   1

In [8]:
y_train # value of class

3    1
1    0
0    0
Name: class, dtype: int64

In [9]:
y_test

2    1
Name: class, dtype: int64

In [10]:
from sklearn.neighbors import KNeighborsClassifier
nn=KNeighborsClassifier(n_neighbors=3)
nn

KNeighborsClassifier(n_neighbors=3)

In [11]:
models=nn.fit(x_train, y_train)
models

KNeighborsClassifier(n_neighbors=3)

In [12]:
y_pred=models.predict(x_test)
y_pred

array([0], dtype=int64)

In [13]:
4*0.2

0.8

In [14]:
# 0.8 = 1
# that means 1 row will be used for testing

In [15]:
if(y_test.iloc[0]==y_pred[0]):
    print("accurate model")
else:
    print("inaccurate model")

inaccurate model


In [16]:
print(type(y_test.iloc[0]), type(y_pred[0]))

<class 'numpy.int64'> <class 'numpy.int64'>


In [17]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
cm

array([[0, 0],
       [1, 0]], dtype=int64)

In [18]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
print(TN, FP, FN, TP)

0 0 1 0


In [19]:
accuracy=(TP+TN)/(TP+TN+FP+FN)
accuracy

0.0

In [20]:
error_rate=(FP+FN)/(TP+TN+FP+FN)
error_rate

1.0

In [21]:
error_rate=1-accuracy
error_rate

1.0

In [22]:
sensitivity=TP/(TP+FN)
sensitivity

0.0

In [23]:
specificity=(TN)/(TN+FP)
specificity
# 0/0=infinity

<ipython-input-23-413f3ab59963>:1: RuntimeWarning: invalid value encountered in longlong_scalars
  specificity=(TN)/(TN+FP)


nan

In [24]:
df=pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [25]:
y=df["Outcome"]
x=df.drop("Outcome", axis=1)
print(x.shape, y.shape)

(768, 8) (768,)


In [26]:
import math
print(math.sqrt(768))

27.712812921102035


In [27]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=2)

In [28]:
nn=KNeighborsClassifier(n_neighbors=29)
nn

KNeighborsClassifier(n_neighbors=29)

In [29]:
models=nn.fit(x_train, y_train)
models

KNeighborsClassifier(n_neighbors=29)

In [30]:
y_pred=models.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [31]:
cm=confusion_matrix(y_test, y_pred)
cm

array([[97, 12],
       [23, 22]], dtype=int64)

In [32]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
print(TN, FP, FN, TP)

97 12 23 22


In [33]:
accuracy=(TP+TN)/(TP+TN+FP+FN)
accuracy

0.7727272727272727

In [34]:
error_rate=(FP+FN)/(TP+TN+FP+FN)
error_rate

0.22727272727272727

In [35]:
error_rate=1-accuracy
error_rate

0.2272727272727273

In [36]:
sensitivity=TP/(TP+FN)
sensitivity

0.4888888888888889

In [37]:
specificity=(TN)/(TN+FP)
specificity

0.8899082568807339