In [146]:
import pandas as pd

In [147]:
df=pd.read_csv("temp.csv")
df

sno  Temperature  Pressure
0    1            0    0.0002
1    2           20    0.0012
2    3           40    0.0060
3    4           60    0.0300
4    5           80    0.0900
5    6          100    0.2700

In [148]:
df=df.drop("sno", axis=1)
df

Temperature  Pressure
0            0    0.0002
1           20    0.0012
2           40    0.0060
3           60    0.0300
4           80    0.0900
5          100    0.2700

In [149]:
y=df["Pressure"]
x=df.drop("Pressure", axis=1)
print(x.shape, y.shape)

(6, 1) (6,)


In [150]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x)
x_poly

array([[1.0e+00, 0.0e+00, 0.0e+00],
       [1.0e+00, 2.0e+01, 4.0e+02],
       [1.0e+00, 4.0e+01, 1.6e+03],
       [1.0e+00, 6.0e+01, 3.6e+03],
       [1.0e+00, 8.0e+01, 6.4e+03],
       [1.0e+00, 1.0e+02, 1.0e+04]])

In [151]:
print(x_poly.shape)

(6, 3)


In [152]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x_poly, y, test_size=0.2)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(4, 3) (2, 3)
(4,) (2,)


In [153]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_train, y_train)

In [154]:
lr.coef_

array([ 0.000e+00, -5.652e-03,  7.300e-05])

In [155]:
lr.intercept_

np.float64(0.09512000000000771)

In [156]:
y_pred=lr.predict(x_test)
y_pred

array([0.0188 , 0.09512])

In [157]:
from sklearn import metrics
print("MSE:", metrics.mean_squared_error(y_test, y_pred))

MSE: 0.004567623200000723


In [158]:
import numpy as np
test_data=np.array([54,67])
print(test_data)
print(test_data.shape)

[54 67]
(2,)


In [159]:
test_data=test_data.reshape(-1,1)
print(test_data)
print(test_data.shape)

[[54]
 [67]]
(2, 1)


In [160]:
test_data=poly.fit_transform(test_data)
test_data

array([[1.000e+00, 5.400e+01, 2.916e+03],
       [1.000e+00, 6.700e+01, 4.489e+03]])

In [161]:
lr.predict(test_data)

array([0.00278 , 0.044133])

In [162]:
df1=pd.read_csv("Real estate.csv")
df1

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [163]:
df1=df1.drop("No", axis=1)
df1

X1 transaction date  X2 house age  \
0               2012.917          32.0   
1               2012.917          19.5   
2               2013.583          13.3   
3               2013.500          13.3   
4               2012.833           5.0   
..                   ...           ...   
409             2013.000          13.7   
410             2012.667           5.6   
411             2013.250          18.8   
412             2013.000           8.1   
413             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 7 columns]

In [164]:
y=df1["Y house price of unit area"]
x=df1.drop("Y house price of unit area", axis=1)
print(x.shape, y.shape)

(414, 6) (414,)


In [165]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(x)
x_poly

array([[1.00000000e+00, 2.01291700e+03, 3.20000000e+01, ...,
        6.24149290e+02, 3.03643739e+03, 1.47720299e+04],
       [1.00000000e+00, 2.01291700e+03, 1.95000000e+01, ...,
        6.24017387e+02, 3.03609828e+03, 1.47718525e+04],
       [1.00000000e+00, 2.01358300e+03, 1.33000000e+01, ...,
        6.24373157e+02, 3.03707359e+03, 1.47729221e+04],
       ...,
       [1.00000000e+00, 2.01325000e+03, 1.88000000e+01, ...,
        6.23961931e+02, 3.03597212e+03, 1.47719376e+04],
       [1.00000000e+00, 2.01300000e+03, 8.10000000e+00, ...,
        6.23338106e+02, 3.03447431e+03, 1.47721345e+04],
       [1.00000000e+00, 2.01350000e+03, 6.50000000e+00, ...,
        6.23717159e+02, 3.03545749e+03, 1.47727252e+04]])

In [166]:
print(x_poly.shape)

(414, 28)


In [167]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x_poly, y, test_size=0.2, random_state=2)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(331, 28) (83, 28)
(331,) (83,)


In [168]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_train, y_train)

In [169]:
lr.coef_

array([ 1.70261314e-02, -1.70748781e+04,  9.65838503e+02,  2.61663168e+01,
        1.08530981e+04, -7.18735276e+01,  5.81232993e+01,  5.31140718e+00,
        1.39999890e-01, -1.65076673e-03,  1.66158474e-02, -1.20503840e+02,
       -1.06648666e+01,  2.22731585e-02, -8.66383258e-05,  1.15988056e-02,
       -9.60978041e+00, -8.30087057e+00, -1.30606531e-06, -1.86582462e-03,
       -2.78529225e-01, -1.30727816e-01, -8.67239022e-03, -1.26090806e+02,
       -6.36538831e+01,  7.37634655e+03, -1.02399116e+03,  1.95281352e+02])

In [170]:
lr.intercept_

np.float64(17133947.689773686)

In [171]:
y_pred=lr.predict(x_test)
y_pred

array([47.84914684, 39.03908117, 22.24200622, 34.65439297, 24.80000353,
       33.15891705, 38.1337653 , 32.7956344 , 42.73568876, 57.69393505,
       45.2911818 , 24.83207274, 40.78665847, 52.5983906 , 50.59511796,
       28.09603004, 37.84293003, 28.54801867, 18.82288302, 18.35824395,
       43.31766011, 15.89601169, 40.06069842, 38.45477512, 26.62148077,
       28.6048201 , 29.67054152, 53.62443239, 15.95203472, 44.70605393,
       55.66450791, 43.98314076, 35.47599438, 49.13561985, 29.60469718,
       19.12318432, 49.83924371, 28.02951014, 32.22367688, 15.35198961,
       22.12949483, 30.06014087, 52.45952422, 39.51142743, 38.53233244,
       50.89924857, 45.7616668 , 17.46804358, 44.94898412, 34.81066414,
       31.39271978, 42.50070742, 50.70276224, 40.65458776, 48.89459266,
       45.48834297, 46.94484201,  7.58870895, 44.39694847, 42.2143498 ,
       18.02724639, 55.07327916, 19.76680535, 47.19084623, 36.54238349,
       47.75128104, 59.94046502, 26.41087794, 16.64779582, 18.28

In [172]:
print("MSE:", metrics.mean_squared_error(y_test, y_pred))

MSE: 96.63954359925738


In [173]:
import numpy as np
test_data=np.array([2012.917,32,84.87882,10,24.98298,121.54024])
print(test_data)
print(test_data.shape)

[2012.917     32.        84.87882   10.        24.98298  121.54024]
(6,)


In [174]:
test_data=test_data.reshape(-1,6)
# -1 rows, 6 columns
print(test_data)
print(test_data.shape)

[[2012.917     32.        84.87882   10.        24.98298  121.54024]]
(1, 6)


In [175]:
test_data=poly.fit_transform(test_data)
test_data

array([[1.00000000e+00, 2.01291700e+03, 3.20000000e+01, 8.48788200e+01,
        1.00000000e+01, 2.49829800e+01, 1.21540240e+02, 4.05183485e+06,
        6.44133440e+04, 1.70854020e+05, 2.01291700e+04, 5.02886652e+04,
        2.44650415e+05, 1.02400000e+03, 2.71612224e+03, 3.20000000e+02,
        7.99455360e+02, 3.88928768e+03, 7.20441408e+03, 8.48788200e+02,
        2.12052586e+03, 1.03161922e+04, 1.00000000e+02, 2.49829800e+02,
        1.21540240e+03, 6.24149290e+02, 3.03643739e+03, 1.47720299e+04]])

In [176]:
lr.predict(test_data)

array([46.0442498])